language: node_js
sudo: false

node_js:
  - '4'
  - '5'
  - '6'

env:
  global:
    # get the latest seneca code from master,
    # to test a specific tagged version set the version like below.
    - SENECA_VER=
  # - SENECA_VER=#v1.3.0

  matrix:
    - TEST_SUITE=senecajs/seneca
    - TEST_SUITE=senecajs/gate-executor
    - TEST_SUITE=senecajs/seneca-entity
    - TEST_SUITE=senecajs/seneca-user
    - TEST_SUITE=senecajs/seneca-transport

before_script:
  - TEST_SUITE_FOLDER=$(basename $TEST_SUITE)
  - echo TEST_SUITE:$TEST_SUITE
  - echo TEST_SUITE_FOLDER:$TEST_SUITE_FOLDER
  - if [ $TEST_SUITE_FOLDER != 'seneca' ]; then
      git clone https://github.com/$TEST_SUITE;
      cd $TEST_SUITE_FOLDER;
      npm i;
      npm uninstall seneca;
      npm install https://github.com/senecajs/seneca$SENECA_VER;
    fi

cache:
  directories:
      - node_modules

after_script:
  - npm run coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b98f41fd6ac7d5740632
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
